import AvailabilityRule, { AvailabilityRuleCreationAttributes } from '../../../models/AvailabilityRule.model';
import { SlotEngineService } from './SlotEngine.service';
import { logger } from '../../../utils/logger.util';
import { NotFoundError } from '../../../utils/error.util';

export const AvailabilityRuleService = {
    /**
     * Create a new rule and materialize it
     */
    async createRule(data: AvailabilityRuleCreationAttributes): Promise<AvailabilityRule> {
        logger.info('Creating availability rule', data);

        const rule = await AvailabilityRule.create(data);

        // Trigger async materialization
        SlotEngineService.materializeRule(rule).catch(err => {
            logger.error(`Error materializing rule ${rule.id} after creation`, err);
        });

        return rule;
    },

    /**
     * Get all rules for a nurse
     */
    async getRulesByNurse(nurseId: string): Promise<AvailabilityRule[]> {
        return await AvailabilityRule.findAll({
            where: { nurse_id: nurseId, is_active: true }
        });
    },

    /**
     * Deactivate a rule
     */
    async deleteRule(ruleId: string, nurseId: string): Promise<void> {
        const rule = await AvailabilityRule.findOne({
            where: { id: ruleId, nurse_id: nurseId }
        });

        if (!rule) {
            throw new NotFoundError('Availability rule not found');
        }

        rule.is_active = false;
        await rule.save();

        // Optionally: Cancel future OPEN slots generated by this rule
        // await AvailabilitySlot.update({ status: SlotStatus.CANCELLED }, { where: { rule_id: ruleId, status: SlotStatus.OPEN } });
    }
};
